

# Inherit global environment
Import('env')
Import('config_symbols')
# The set of source files associated with this SConscript file.
src_local = ['printk.c', 'putc.c', 'string.c', 'bit.c', 'wait.c', 'mutex.c', 'idpool.c', 'memcache.c']
if "ARCH_TEST" not in config_symbols:
	obj = env.Object(src_local)
else:
	obj = []
Return('obj')
