

# Inherit global environment
Import('env')

# The set of source files associated with this SConscript file.
src_local = ['physmem.c', 'irq.c', 'scheduler.c', 'time.c', 'tcb.c', 'pgalloc.c', 'kmalloc.c', 'space.c']

obj = env.Object(src_local)
Return('obj')
