# -*- mode: python; coding: utf-8; -*-

#  Codezero -- a microkernel for embedded systems.
#
#  Copyright © 2009  B Labs Ltd
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU
#  General Public License as published by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.
#
#  Author: Russel Winder

Import ( 'environment' )

e = environment.Clone ( )
e.Append ( CPPPATH = [ 'include' , '#libs/c/include/' , '#tasks/libl4/include'  , '#tasks/libmem' , '#tasks/libposix/include' ] )

#  TODO:  There are errors in this code that -Werror gives problems with.

#e['CCFLAGS'] = [ '-g' , '-nostdlib' , '-Wall' , '-ffreestanding' , '-std=gnu99' , '-D__USERSPACE__' ]

objects = e.StaticObject ( Glob ( '*.c' ) + Glob ( 'src/*.c' ) )
Depends ( objects , e['configFiles'] )
library = e.Program ( 'test0' , objects + [ e['crt0'] ] )

Return ( 'library' )
