#ifndef __MM0_PROC__
#define __MM0_PROC__

struct proc_files {
	struct vm_file *stackfile;	/* ZI, private, devzero, then autogenerated */
	struct vm_file *envfile;	/* NON-ZI, private, autogenerated, then autogenerated */
	struct vm_file *datafile;	/* NON-ZI, private, real file, then autogenerated */
	struct vm_file *bssfile;	/* ZI private, devzero, then autogenerated */
};

int task_prepare_procfiles(struct tcb *t);

#endif
