# -*- mode: python; coding: utf-8; -*-
#
#  Codezero -- Virtualization microkernel for embedded systems.
#
#  Copyright © 2009  B Labs Ltd

import os, sys

# Get global paths
PROJRELROOT = '../..'

sys.path.append(PROJRELROOT)

from config.projpaths import *

Import('env')

e = env.Clone()
e.Append(CPPPATH = ['include/l4thread'])

source = [Glob('*.[cS]') + Glob('src/*.[cS]')]
objects = e.StaticObject(source)
library = e.StaticLibrary('l4thread', objects)

Return('library')
