# -*- mode: python; coding: utf-8; -*-

#  Codezero -- A Virtualization microkernel for embedded systems.
#
#  Copyright © 2009  B Labs Ltd

Import('env')

e = env.Clone()
e.Append(CPPPATH = ['include', 'include/posix'])
e.Replace(CCFLAGS = ['-g', '-nostdlib', '-Wall', '-ffreestanding', '-std=gnu99'])

objects = e.StaticObject(Glob('*.c'))
libposix = e.StaticLibrary('posix', objects)

Return('libposix')
