# -*- mode: python; coding: utf-8; -*-
#
#  Codezero -- a microkernel for embedded systems.
#
#  Copyright © 2009  B Labs Ltd

import os, sys, shelve
from os.path import join

Import('env')

src = Glob('*.[cS]')
objs = env.Object(src)

Return('objs')
