

# Inherit global environment
Import('env')

# The set of source files associated with this SConscript file.
src_local = ['printascii.S','platform.c', 'uart.c', 'timer.c', 'irq.c']

obj = env.Object(src_local)
Return('obj')
