#
# Build script to autogenerate and compile a container image
#
# Copyright (C) 2009 B Labs
#
import os
from os.path import join

Import('environment')

cwd = os.getcwd()

os.chdir("/opt/codezero/conts/linux")

os.system("scons")

image = []
image.append(File("container.elf"))

os.chdir(cwd)

Return('image')
