

# Inherit global environment
Import('env')

# The set of source files associated with this SConscript file.
src_local = ['init.c', 'memory.c', 'systable.c']

obj = env.Object(src_local)
Return('obj')
