
# Inherit global environment
import os, sys

PROJRELROOT = '../../../'
sys.path.append(PROJRELROOT)

from scripts.config.projpaths import *
from scripts.config.config_invoke import *

Import('env')

# The set of source files associated with this SConscript file.
src_local = ['platform.c', 'irq.c']
obj = env.Object(src_local)

# This is arealview platform, include corresponding files.
obj += SConscript(join(PROJROOT, 'src/platform/realview/SConscript'),
                  exports = {'env' : env }, duplicate = 0,
                  build_dir = 'realview')

Return('obj')
