#ifndef __INITTASK_ARCH_OFFSETS_H__
#define __INITTASK_ARCH_OFFSETS_H__

#define INITTASK_AREA_START	0xE0000000
#define INITTASK_AREA_END	0xF0000000

#define INITTASK_OFFSET		INITTASK_AREA_START

#endif
